---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nachobot

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nachobot-config
  namespace: nachobot
data:
  PORT: "3000"
  DAILY_NACHO_LIMIT: "5"
  TZ: "America/New_York"

---
# Secret for sensitive credentials
# Note: Create this manually with kubectl:
# kubectl create secret generic nachobot-secrets \
#   --from-literal=SLACK_BOT_TOKEN=xoxb-your-token \
#   --from-literal=SLACK_APP_TOKEN=xapp-your-token \
#   --from-literal=SLACK_SIGNING_SECRET=your-secret \
#   --from-literal=MONGODB_URI=mongodb+srv://user:pass@host/database \
#   -n nachobot

---
# NachoBot Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nachobot
  namespace: nachobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nachobot
  template:
    metadata:
      labels:
        app: nachobot
    spec:
      containers:
        - name: nachobot
          image: ghcr.io/bytenik/heynacho:latest
          imagePullPolicy: Always
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nachobot-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nachobot-secrets
                  key: SLACK_APP_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: nachobot-secrets
                  key: SLACK_SIGNING_SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: nachobot-secrets
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: nachobot-config
                  key: PORT
            - name: DAILY_NACHO_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: nachobot-config
                  key: DAILY_NACHO_LIMIT
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: nachobot-config
                  key: TZ
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
